# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jhonny F. Dutra
email: jfreitasdutra@gmail.com
description: Em desenvolvimento
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jfreitasdutra.github.io" # the base hostname & protocol for your site
twitter_username: jfreitasdutra
github_username:  jfreitasdutra

# Build settings
markdown: kramdown
